server:
  port: 9004

spring:
  application:
    name: emart-item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:127.0.0.1}:${DB_PORT:3306}/${DB_SCHEMA:item_db}
    username: ${DB_USERNAME:item_db}
    password: ${DB_PASSWORD:Item123}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:9999/eureka/}